#!/usr/bin/env python
import sys  
import json
import operator  # for object manipulation

def main():  
  sent_file = open(sys.argv[1])  
  tweet_file = open(sys.argv[2])  

  scores = {}   # an empty dictionary  
  for line in sent_file:  
   term, score = line.split("\t")   # splitting on tab delimiter  
   scores[term] = int(score)        # Convert the score to an integer.  

  happiness={} #for containing {state, sentiment}  

  for line in tweet_file:  
	   #from file into a json object  
	   mystr = json.loads(line)  
	   #check for US  
	   if 'place' in mystr.keys() and mystr["place"] is not None and mystr["place"]["country_code"]=='US':  
			#check for state - 2 characters
			if 'user' in mystr.keys() and mystr["user"] is not None and mystr["user"]["location"] is not None:  
				 location=mystr["user"]["location"].split(' ')  
				 if len(location)==2 and len(location[1])==2:  
					  if 'text' in mystr.keys():  
						   resscore=0  
						   #split the tweet into a list of words  
						   words = mystr["text"].split()  
						   for word in words:  
								#if the current word exists in our dictionary, add its value to the total  
								if word in scores:  
									 resscore+=scores[word]  
						   #to float  
						   resscore+=0.0  
						   #store states happiness  
						   if location[1] not in happiness:  
								happiness[location[1]]=resscore  
						   else:  
								happiness[location[1]]+=resscore  
  #create a file that contains a list of happiness and print out the name of the lucky ont to stdout
  if len(happiness.keys())>0:
  		themosthappieststate = max(happiness.iteritems(), key=operator.itemgetter(1))[0]
  		with open('happy_states_scores.txt', 'w') as happ_list: 
	   	    json.dump(happiness, happ_list)
	   	    
	   	print themosthappieststate
  else:  
	   print 'US'  

if __name__ == '__main__':  
  main()  
